Restaurant app
yamilacasarini/restopassApp pull request #13
Opened 2020-08-10 13:29 UTC by yamilacasarini

2020-08-13 02:22 UTC, juanicabanas requested changes

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true">
qué es esto?

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/connection/interceptor/AuthInterceptor.kt
> +             LoginService.refreshRestaurantToken(AppPreferences.accessToken!!, AppPreferences.refreshToken!!)
creo que podés simplificar todo empezando desde acá haciendo
**val response = if (AppPrefereces.restaurantUser != null) runBlocking { ... } else runBlocking {...}** 

total, después es todo lo mismo y lo que sí preguntás de nuevo con ese if para ver si seteas **restaurantUser** o **user**

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/domain/Reservation.kt
> +    val dinnersPerMembership: Map<String, Long>
un Long?

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/RestaurantActivity.kt
> +            resultCode, data
qué es esto? no entiendo

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +        return name[0] + "\n" + name[1]
return "${name[0]} \n ${name[1]}

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +            date.dayOfMonth.toString() + "/" + date.monthValue.toString() + "\n" + date.hour + ":0" + date.minute
ídem acá con armar los strings. queda mucho más legible

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +            date.dayOfMonth.toString() + "/" + date.monthValue.toString() + "\n" + date.hour + ":" + date.minute
ídem

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/settings/RestaurantSettingsFragment.kt
> +            )
y esta fumeta? jajajaj

2020-08-13 02:22 UTC, juanicabanas commented on app/src/main/res/values/strings.xml
> +
vayamos por camelCase o snake_case pero no ambas jajaja. la mayoría está como camelCase así que fijate de cambiarlo de última (boludez igual)

2020-08-14 22:23 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/domain/Reservation.kt
> +    val dinnersPerMembership: Map<String, Long>
Si quedo de la respuesta de tefi no lo modifique, tampoco cambia tanto

2020-08-14 22:23 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/connection/interceptor/AuthInterceptor.kt
> +             LoginService.refreshRestaurantToken(AppPreferences.accessToken!!, AppPreferences.refreshToken!!)
Sisi ya lo cambie

2020-08-14 22:23 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/RestaurantActivity.kt
> +            resultCode, data
Esto es el resultado de la lectura del QR

2020-08-14 22:24 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/settings/RestaurantSettingsFragment.kt
> +            )
Es para tener sizes distintos en un mismo text view

2020-08-14 22:24 UTC, yamilacasarini commented on app/src/main/res/values/strings.xml
> +
si pasa que son un monton, despues lo metemos en otro pr eso

2020-08-14 22:37 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +            date.dayOfMonth.toString() + "/" + date.monthValue.toString() + "\n" + date.hour + ":0" + date.minute
cambiado

2020-08-14 22:37 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +            date.dayOfMonth.toString() + "/" + date.monthValue.toString() + "\n" + date.hour + ":" + date.minute
cambiado

2020-08-14 22:37 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/RestaurantDishesFragment.kt
> +        return name[0] + "\n" + name[1]
cambiado

2020-08-14 22:41 UTC, yamilacasarini commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true">
nose, se habra metido cuando probe algo, lo saque porque no sirve de nada

2020-08-14 22:43 UTC, yamilacasarini commented on app/src/main/res/values/strings.xml
> +
lo mismo pasa en los xmls creo. Eso si es mas paja cambiarlos

2020-08-14 23:38 UTC, juanicabanas commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CAMERA"/>
tenés idea si por más que seas usuario final (no restaurant) se te pide los permisos de la cámara al iniciar la app? porque no se necesitarían. solo una duda

2020-08-14 23:38 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/QRActivity.kt
> +            findNavController(R.id.nav_host_fragment_restaurant).navigate(R.id.restaurantDishesFragment)
por qué tenés un RestaurantActivity y después este otro? Nos estamos basando en tener laa menor cantidad de Activities posibles y manejarnos con fragments, por lo que lo ideal sería que sea solo uno

2020-08-14 23:38 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/QRActivity.kt
> +    val activity : Activity? = null;
por qué tenés un atributo que es un activity?

2020-08-14 23:38 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/restaurantApp/ui/settings/RestaurantSettingsFragment.kt
> +            )
y por qué sizes distintos?

2020-08-14 23:38 UTC, juanicabanas commented on app/src/main/res/values/strings.xml
> +
sí, pero cuanto menos arrastremos el error mejor. tengamos eso en cuenta para las próximas

2020-08-15 00:25 UTC, yamilacasarini commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CAMERA"/>
nono, no se piden en ninguno de los dos casos. Se piden recien cuando tocas el boton que abre la camara (en nuestro caso el boton de escanear QR)

2020-08-15 00:26 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/QRActivity.kt
> +            findNavController(R.id.nav_host_fragment_restaurant).navigate(R.id.restaurantDishesFragment)
Porque lo tenes que hacer asi para el lector de qr, necesita su activity aparte

2020-08-15 00:28 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/home/QRActivity.kt
> +    val activity : Activity? = null;
no nada, esto quedo. Puede estar la clase vacia directamente

2020-08-15 00:28 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/restaurantApp/ui/settings/RestaurantSettingsFragment.kt
> +            )
es para donde se muestran las estrellas (2.5/5) el sobre 5 es mas chico

2020-08-15 01:10 UTC, juanicabanas approved these changes

2020-08-15 02:09 UTC, merged