Delete user
yamilacasarini/restopassApp pull request #15
Opened 2020-08-22 05:40 UTC by yamilacasarini

2020-08-24 22:11 UTC, juanicabanas approved these changes

2020-08-24 22:11 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/ui/settings/personalInfo/PersonalInfoFragment.kt
> +                personalInfoSection.visibility = View.VISIBLE
esto lo probaste? el AppPreferences.logout() te mata el activity y te abre el del login. si llamás a esto después de eso puede que explota todo porque no encontraría a estas views

2020-09-13 23:57 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/main/ui/settings/personalInfo/PersonalInfoFragment.kt
> +                personalInfoSection.visibility = View.VISIBLE
Si anda, igual lo borre porque si esta al pedo

2020-09-14 19:39 UTC, juanicabanas requested changes

2020-09-14 19:39 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/service/LoginService.kt
> +        @POST("/users/create")
esto lo cambiaste en el back? no lo vi

2020-09-14 19:39 UTC, juanicabanas commented on app/src/main/res/values/strings.xml
> +    <string name="deleteAccount"><![CDATA[Estas por eliminar tu cuenta de forma permanente.
Estás
```suggestion
    <string name="deleteAccount"><![CDATA[Estás por eliminar tu cuenta de forma permanente.
```

2020-09-14 19:39 UTC, juanicabanas commented on app/src/main/java/com/example/restopass/main/common/AlertDialog.kt
> +            action(body.deleteAccountInputText.text.toString().md5())
Tratemos de simplificar los AlertDialog que ya son un bardo en sí. Hay una función que hace esto mismo que es getActionDialogWithParams en AlertDialog.kt genérica

2020-09-14 19:40 UTC, yamilacasarini commented on app/src/main/res/values/strings.xml
> +    <string name="deleteAccount"><![CDATA[Estas por eliminar tu cuenta de forma permanente.
ayayayayayyaya

2020-09-14 19:42 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/main/common/AlertDialog.kt
> +            action(body.deleteAccountInputText.text.toString().md5())
Es parecida pero no es lo mismo, en esta obtengo el valor del input text del dialog

2020-09-14 19:43 UTC, yamilacasarini commented on app/src/main/java/com/example/restopass/service/LoginService.kt
> +        @POST("/users/create")
No, se me paso. Ahi lo cambie en el PR del back, lo subo con eso

2020-09-14 23:59 UTC, merged